CREATE TABLE IF NOT EXISTS ESCOLA.TIPO_SERIE (
    ID CHAR(36) NOT NULL,
    NOME VARCHAR(255),
    DATA_INSERCAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_ALTERACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
)
